services:
  beesknees:
    build: .
    ports:
      - "3000:3000"
    environment:
      - GOOGLE_API_KEY=AIzaSyBodEo-Lbzg2al-4_nmLTXBFSW4VrS4nfI
      - FOURSQUARE_API_KEY=GKBKSLTO13YCILAF3ZTKQ2P0V3QCPAJQDOSJSVXUAK4W3IW5
    restart: unless-stopped
